### ISSUE TITLE
Help to resolve crash `(iolib::SimpleMultiPlayer::onAudioReady(oboe::AudioStream*, void*, int))`

### ISSUE THREAD

**Issue by antonioolf** [google/oboe#1663]
Hello guys. I have an app, [Mega Drum](https://play.google.com/store/apps/details?id=com.oliveiralabs.megadrum), a drum simulator that uses the oboe.

To be more specific, I'm basically using the Drumthumper sample as a base to play the sounds.

So far I haven't made any modifications to Drumthumper's C++ code, as I don't have enough knowledge in C++/NDK. Also, the C++ implemented for Drumthumper is enough to make the sounds played in Mega Drum functional and allows me to focus on the rest of the App development.

The problem is that it's been a while since I've been suffering from a crash reported on Google Play, and due to lack of knowledge in C++ I can't find a solution.

Could you help me to resolve?

### Crash details from Google Play Console:

`iolib::SimpleMultiPlayer::onAudioReady(oboe::AudioStream*, void*, int)`

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.oliveiralabs.megadrum <<<

backtrace:
  #00  pc 0x000000000006529e  /data/app/~~tzT0ITOnAw-4mQ6Mss5AQQ==/com.oliveiralabs.megadrum-r_a-sFzxpRTkQ3FFl4UpQQ==/split_config.arm64_v8a.apk!libinstrument.so
  #01  pc 0x000000000008269c  /data/app/~~tzT0ITOnAw-4mQ6Mss5AQQ==/com.oliveiralabs.megadrum-r_a-sFzxpRTkQ3FFl4UpQQ==/split_config.arm64_v8a.apk!libinstrument.so (iolib::SimpleMultiPlayer::onAudioReady(oboe::AudioStream*, void*, int)+40)
  #02  pc 0x0000000000085ad4  /data/app/~~tzT0ITOnAw-4mQ6Mss5AQQ==/com.oliveiralabs.megadrum-r_a-sFzxpRTkQ3FFl4UpQQ==/split_config.arm64_v8a.apk!libinstrument.so (oboe::AudioStream::fireDataCallback(void*, int)+104)
  #03  pc 0x00000000000886e0  /data/app/~~tzT0ITOnAw-4mQ6Mss5AQQ==/com.oliveiralabs.megadrum-r_a-sFzxpRTkQ3FFl4UpQQ==/split_config.arm64_v8a.apk!libinstrument.so (oboe::AudioStreamAAudio::callOnAudioReady(AAudioStreamStruct*, void*, int)+40)
  #04  pc 0x0000000000022364  /system/lib64/libaaudio_internal.so (aaudio::AudioStream::maybeCallDataCallback(void*, int)+192)
  #05  pc 0x000000000002432c  /system/lib64/libaaudio_internal.so (aaudio::AudioStreamLegacy::callDataCallbackFrames(unsigned char*, int)+300)
  #06  pc 0x0000000000024980  /system/lib64/libaaudio_internal.so (aaudio::AudioStreamLegacy::processCallbackCommon(int, void*)+952)
  #07  pc 0x0000000000086200  /system/lib64/libaudioclient.so (android::AudioTrack::processAudioBuffer()+2408)
  #08  pc 0x00000000000855a8  /system/lib64/libaudioclient.so (android::AudioTrack::AudioTrackThread::threadLoop()+272)
  #09  pc 0x0000000000015594  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+460)
  #10  pc 0x00000000000a4490  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+144)
  #11  pc 0x0000000000014d90  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412)
  #12  pc 0x00000000000da278  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #13  pc 0x000000000007a448  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

**Comment by philburk** [comment]
@antoniolf - Is there any more information in the Play Store console?
For example does it give the cause of the abort? SIGSEGV?
Does it list the Android version when the crash occurs?
Does it happen more on some devices than others?
Can you repro the crash?
How often does it happen?

Is there any chance you are deleting the callback object immediately after the stream is closed?  A race condition could cause a late callback with Legacy streams.

**Comment by philburk** [comment]
@android-usb - Have you seen any crashes in the DrumThumper console on Play Store?

**Comment by antonioolf** [comment]
@philburk Answering your questions:

**Is there any more information in the Play Store console?**

On the google play crash details page there are other data related to the number of occurrences, number of occurrences by android version, app version, device model etc, in addition to the stacktrace that I posted. (I will attach a screenshot of the details screen, if you allow me).

**For example does it give the cause of the abort? SIGSEGV?**

I remember that until a while ago there was this term "SIGSEGV" on that same error details page. But I think there might have been some update on the google play console, and now that keyword is not there anymore. But it's the same error, with the same stacktrace.

**Does it list the Android version when the crash occurs?** and **Can you repro the crash?**

Unfortunately I haven't been able to reproduce this problem yet, so I haven't even been able to do any experiments to try to fix it. All I've tried so far has been "shots in the dark". (That's why I decided to ask for help here)

**Does it happen more on some devices than others?**

From the data that google play shows, the occurrence of the error in relation to the device model seems to be well distributed, so I imagine that it is not something related to a specific model.

**How often does it happen?**
The error occurs at a very high frequency, unfortunately.
According to the Google play console they were: 8240 events in the last 28 days, 42.2% of users.

**Comment by antonioolf** [comment]
![mega-drum](https://user-images.githubusercontent.com/6179632/204372963-e6654735-fbce-4daf-8a51-e77fd93bab9c.png)

**Comment by antonioolf** [comment]
@philburk About your question "**_Is there any chance you are deleting the callback object immediately after the stream is closed? A race condition could cause a late callback with Legacy streams._**", could this code be an example of it?

```
override fun onStop() {
    mInstrumentPlayer.teardownAudioStream()
    mInstrumentPlayer.unloadWavAssets()

    super.onStop()
}
```

I run it on 2 different occasions in my main activity. This was the way I found to solve a bug that was making the audio distort when the user turned the screen off and on again.

**Comment by robertwu1** [comment]
Seems like DrumThumper is still using setCallback() instead of setDataCallback() and setErrorCallback(). @android-usb can you make the appropriate changes to DrumThumper? See #1661

**Comment by antonioolf** [comment]
@robertwu1 @philburk @android-usb Any news?
Ps: Sorry for the insistence, this problem is taking my sleep. =\

**Comment by philburk** [comment]
I am concerned about the way that WAV assets are handled in DrumThumper.
I will review that code with the author.

@antonioolf - Are you using the code that restarts the audio from Java?
It is enabled by setting mUseDeviceChangeFallback = true in DrumThumperActivity.java.
I am concerned that it might cause race conditions when headsets are unplugged. If you changed it to true then try setting it false.

**Comment by antonioolf** [comment]
@philburk, this is an interesting point for us to investigate. I'm currently not using that part of Drumthumper's code.

Despite not having made any changes to the "DrumPlayerJNI.cpp" file or any other file in the "iolib" lib, I naturally adapted "DrumThumperActivity" to become the main activity of my Mega Drum application. With that, one of the adaptations I made (maybe that's the issue) I ended up completely removing the inner class "DeviceListener", because it wasn't very clear to me what would happen if the activity wasn't present in the code.

Do you suggest to add again the "DeviceListener" class implementation and the code snippet below in the "onStop" and "onStart" methods?

```kotlin
if (mUseDeviceChangeFallback) {
    mAudioMgr!!.registerAudioDeviceCallback(mDeviceListener, null)
}
```

**Comment by antonioolf** [comment]
Okay @philburk, I get it. Do you suggest any way around this crashes until we reach a definitive solution? Just to stop the massive amount of crashes reported by the Google Play console.

Something like simple a try-catch in SimpleMultiPlayer::onAudioReady or something like that somewhere else.

**Comment by philburk** [comment]
The problem is that the data callback is still running while something is getting deleted.
There were problems in the Legacy data path AudioTrack involving joining the callback thread from the AudioTrack destructor.  This was fixed in Android 12 but you are seeing crashes in Android 12 so that may not be the issue.

https://cs.android.com/android/_/android/platform/frameworks/av/+/7a9577cbb13a5d5cf85918ff746f098ae75dd1c6

I think we need to update DrumThumper to use shared_ptr for separate data and error callbacks. See #1626 

Also you can use the latest Oboe and set a delay between the stop and close calls in Oboe. See #1593

    AudioStream::setDelayBeforeCloseMillis(delay)

You could also add a short sleep, (50 msec?), in onStop():

    mInstrumentPlayer.teardownAudioStream()
    // add a sleep here
    mInstrumentPlayer.unloadWavAssets()

I don't know exactly what is failing but these steps will probably help.

**Comment by antonioolf** [comment]
@robertwu1 and @philburk 
First of all, thank you very much for your attention and effort.
I've already uploaded a new version of Mega Drum containing the update made by @robertwu1 (I confess that I was hopeful when I saw the update on this issue)

But unfortunately the error persists... Follow the new stack trace.
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 8161 >>> com.oliveiralabs.megadrum <<<

backtrace:
  Unknown
  #01  pc 0x000000000005a9e9  /data/app/com.oliveiralabs.megadrum-jAvSuzdhvCvZ-YxyEih-6w==/split_config.armeabi_v7a.apk!libinstrument.so (iolib::SimpleMultiPlayer::MyDataCallback::onAudioReady(oboe::AudioStream*, void*, int)+44)
  #02  pc 0x000000000005cd85  /data/app/com.oliveiralabs.megadrum-jAvSuzdhvCvZ-YxyEih-6w==/split_config.armeabi_v7a.apk!libinstrument.so (oboe::AudioStream::fireDataCallback(void*, int)+63)
  #03  pc 0x000000000005ed05  /data/app/com.oliveiralabs.megadrum-jAvSuzdhvCvZ-YxyEih-6w==/split_config.armeabi_v7a.apk!libinstrument.so (oboe::AudioStreamAAudio::callOnAudioReady(AAudioStreamStruct*, void*, int)+396)
  #04  pc 0x0000000000013b31  /system/lib/libaaudio.so (aaudio::AudioStream::maybeCallDataCallback(void*, int)+44)
  #05  pc 0x0000000000014ebb  /system/lib/libaaudio.so (aaudio::AudioStreamLegacy::processCallbackCommon(int, void*)+318)
  #06  pc 0x00000000000413e3  /system/lib/libaudioclient.so (android::AudioTrack::processAudioBuffer()+1802)
  #07  pc 0x0000000000042f17  /system/lib/libaudioclient.so (android::AudioTrack::AudioTrackThread::threadLoop()+130)
  #08  pc 0x000000000000da1d  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+156)
  #09  pc 0x0000000000081af9  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+88)
  #10  pc 0x00000000000aa8bb  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #11  pc 0x0000000000061993  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
  ```

If possible, can you send me some c++ code snippet so I can quickly test it, even if it's just to test some hypothesis of what could solve the problem.

What do you think?

**Comment by philburk** [comment]
Is it possible your crash is occuring when you rotate the phone? It will stop and restart the app.

Also try plugging and unplugging headsets to make it crash. That can cause problems.

Try removing this from onStop()
    mInstrumentPlayer.unloadWavAssets()
And move the loading of WavAssets to the onCreate() method.

Are you sure the crashes are in the latest version of your app? The one with your fixes?

**Comment by antonioolf** [comment]
@philburk Answering:
**Is it possible your crash is occuring when you rotate the phone? It will stop and restart the app.**

I did a test here doing some rotations, and there was no relevant log. Anyway that was the log of two screen rotations.: https://gist.github.com/antonioolf/3144d2d78c80a4aa182ba29beb0eab2d

**Also try plugging and unplugging headsets to make it crash. That can cause problems.**

I've tested plugging and unplugging the headset, and something suspicious seems to have happened. Here is the log: https://gist.github.com/antonioolf/726e7f00e9324ce8543ed819cbee98e5

I followed the error happening in the debugger, it starts in the method `AudioStreamAAudio.cpp -> oboe_aaudio_error_thread_proc_shared`, and passing through `oboe_aaudio_error_thread_proc` the call `errorCallback->onError(oboeStream, error);` returns the default value `false` in `AudioStreamCallback.h` and makes the code call `void SimpleMultiPlayer::MyErrorCallback::onErrorAfterClose` which shows that log with the snippet `==== onErrorAfterClose() error:-899`

Despite this error log, when this happens the app continues to function normally, there is no crash, freezing or sudden closure.

**Try removing this from onStop()
mInstrumentPlayer.unloadWavAssets()**

I will do that and release a new release (4.0.4)

**And move the loading of WavAssets to the onCreate() method.**

I'm going to test that too, but in this case I'll take a little more time to be able to do it carefully and not run the risk of breaking anything. Today the call to the method that loads the wav files (mInstrumentPlayer.loadWavAssets(getAssets())) occurs from other methods that initially start with the onResume() call.

As soon as we eliminate other possibilities I will make this change so that we can verify.

**Are you sure the crashes are in the latest version of your app? The one with your fixes?**

Yes, this log is from the latest version I released after updating [my Oboe fork](https://github.com/antonioolf/oboe). I'm pretty sure (unless I'm doing something really wrong)

Some evidence follows:

![Screenshot from 2023-03-18 15-34-13](https://user-images.githubusercontent.com/6179632/226133731-55fd7110-b953-4be5-9354-adfbfaefedbf.png)
![Screenshot from 2023-03-18 15-32-45](https://user-images.githubusercontent.com/6179632/226133739-6c3da203-4d14-4eb5-8a52-f4e539294851.png)

If you have anything else that could be tested for research purposes, please don't hesitate to let me know.
If you want, I can also privately show any part of my app's code in full for any of you, the main activity for example.

**Comment by philburk** [comment]
Thanks for sharing the logs:
> onErrorAfterClose() error:-899
> Despite this error log, when this happens the app continues to function normally,

The error -899 means the stream was disconnected.  That happens when you unplug or plug in a headset.  It's not really an error but AAudio sees the device disappear so it can't play any more and the stream is dead. I guss we could call it an expected error.

I notice that the data path alternates between MMAP and Legacy AudioTrack. That might be because you are on a device that only supports MMAP on the headset and not the speaker. Some MediaTek devices do that.
What Android device and OS version was that log from?

This log is interesting:
> releaseBuffer is no-op due to IAudioTrack sequence mismatch 1 != 2

That is a log from a fix that would have caused a crash on earlier versions of Android, 10(Q) or earlier. So probably not related.
https://github.com/google/oboe/wiki/TechNote_ReleaseBuffer

**Comment by antonioolf** [comment]
I am using my personal smartphone: `motorola edge 20 lite / Android Version: 12`

I was thinking about the following, although it is not the definitive solution, would it be a good idea to put a try catch in the `onAudioReady` method? Something like that:

```
DataCallbackResult SimpleMultiPlayer::MyDataCallback::onAudioReady(AudioStream *oboeStream,
                                                                   void *audioData,
                                                                   int32_t numFrames) {
    try {
        StreamState streamState = oboeStream->getState();
        if (streamState != StreamState::Open && streamState != StreamState::Started) {
            __android_log_print(ANDROID_LOG_ERROR, TAG, "  streamState:%d", streamState);
        }
        if (streamState == StreamState::Disconnected) {
            __android_log_print(ANDROID_LOG_ERROR, TAG, "  streamState::Disconnected");
        }

        memset(audioData, 0, static_cast<size_t>(numFrames) * static_cast<size_t>
                (mParent->mChannelCount) * sizeof(float));

        // OneShotSampleSource* sources = mSampleSources.get();
        for(int32_t index = 0; index < mParent->mNumSampleBuffers; index++) {
            if (mParent->mSampleSources[index]->isPlaying()) {
                mParent->mSampleSources[index]->mixAudio((float*)audioData, mParent->mChannelCount,
                                                         numFrames);
            }
        }
    } catch (const std::exception& ex) {
        __android_log_print(ANDROID_LOG_ERROR, TAG, "Exception caught in onAudioReady: %s", ex.what());
    }
    return DataCallbackResult::Continue;
}
```

In this way, perhaps at least the percentage of crashes per session on the Google Play console would be reduced while we do not find the definitive solution. What do you think?

**Comment by antonioolf** [comment]
@philburk I found something interesting, take a look at this log: https://gist.github.com/antonioolf/7f6978fdfb894870d4b39abcba848ebb

I captured it while clicking on an option that opens an interstitial ad, visualizing all of its content and then closing, returning to main activity again.

See the log has the following line:
```
OboeAudio               com.oliveiralabs.megadrum  W  AudioStream::fireDataCallback() called with data callback disabled!
```

which has `fireDataCallback` which is shown in the error reported by Google Play. Also, the block that shows this log has the following comment  in the next line (you are as author :P)
```
// Should not be getting called
```

**Comment by robertwu1** [comment]
Line 44 of your crash seems to indicate that `StreamState streamState = oboeStream->getState();` is crashing.
```
#01  pc 0x000000000005a9e9  /data/app/com.oliveiralabs.megadrum-jAvSuzdhvCvZ-YxyEih-6w==/split_config.armeabi_v7a.apk!libinstrument.so (iolib::SimpleMultiPlayer::MyDataCallback::onAudioReady(oboe::AudioStream*, void*, int)+44)
```

This implies that the oboeStream pointer is somehow null now. Can you add a null pointer check there?

~~~
    if (oboeStream == nullptr) {
        __android_log_print(ANDROID_LOG_ERROR, TAG, "oboeStream null");
        return DataCallbackResult::Stop;
    }
~~~

**Comment by philburk** [comment]
I think you may be hitting this bug that we have just discovered. #1763
Please try running your app while connecting and disconnecting a Bluetooth headset.
Does that eventually trigger a crash?

**Comment by antonioolf** [comment]
@philburk I believe this is the way to go!
Sorry for the delay in answering, I've been doing several tests turning bluetooth on/off with my personal device (`motorola edge 20 lite`) since you commented, but without any success.

Today I had the idea to test with an older device I have (`Motorola Moto z3 play`) and the error log referencing `SimpleMultiPlayer::MyDataCallback::onAudioReady` finally appeared when I connected to a bluetooth headset for the first time.

For some reason I couldn't get it to show up again after that. Neither connecting, disconnecting the headphones nor turning bluetooth on and off. I wish I could capture the full log to post here.

But I would like to signal this progress, I believe that the solution is now close.

**Comment by philburk** [comment]
OboeTester now has a new test called "Routing Stress" that will toggle the SpeakerPhone on/off. This will trigger routing changes similar to plugging in or unplugging a headset. One some devices it will crash right away. #1760

**Comment by antonioolf** [comment]
@philburk Sorry for the question, any estimates on when the definitive fix for this problem will be released?
